"""Markdown report for the simulation run; every number comes from reports/sim_results.json."""

from __future__ import annotations


def _pct(x: float) -> str:
    return f"{x:.1%}"


def render(res: dict, manifest_name: str) -> str:
    cfg = res["config"]
    a = res["A"]
    L = [
        "# Simulation report",
        "",
        f"Generated by `eduai simulate` ({cfg['students']} synthetic students per condition, seed {cfg['seed']}, "
        f"subject {cfg['subject']}, {cfg['per_lo']} items per LO). Run time {res['seconds']} s. "
        f"Manifest: `{manifest_name}`.",
        "",
        "Everything here is a simulation under stated assumptions (see `src/eduai/sim/students.py`). "
        "Responses are drawn from the same model the system uses, so these results show that the "
        "estimators and policies behave as designed when the model is right; they say nothing about "
        "real students.",
        "",
        f"Response model: p = c + (1 - c) sigmoid(theta - b), c = 0.25. Fisher information peaks at "
        f"p* = {a['p_star']:.3f}, where one item carries I = {a['max_item_information']:.3f}.",
        "",
        "## A. Assessment",
        "",
        "![A](figures/sim_a_rmse.png)",
        "",
        "RMSE of the EAP estimate by test length (fixed length, no early stop):",
        "",
    ]
    curves = a["rmse_by_length"]
    lengths = list(next(iter(curves.values())).keys())
    L.append("| Policy | " + " | ".join(f"{n} items" for n in lengths) + " |")
    L.append("|---|" + "---|" * len(lengths))
    for name, curve in curves.items():
        L.append(f"| {name} | " + " | ".join(f"{curve[n]:.3f}" for n in lengths) + " |")
    L += [
        "",
        "Calibration under the stopping rule (stop when the EAP posterior SD drops below the threshold, "
        f"or at {cfg['a_max_stop']} items). Coverage is the share of students whose true theta falls in "
        "theta-hat +/- 1.96 SD. 1/sqrt(sum I) is shown for comparison only; it is not used to stop.",
        "",
        "| SD threshold | Coverage (95% target) | RMSE | Mean reported SD | Mean 1/sqrt(sum I) | Mean length | "
        "Median length | Stopped by precision |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for s in a["stopping"]:
        L.append(
            f"| {s['sd_stop']} | {_pct(s['coverage_95'])} | {s['rmse']:.3f} | {s['mean_reported_sd']:.3f} | "
            f"{s['mean_info_se']:.3f} | {s['mean_length']:.1f} | {s['median_length']:.0f} | "
            f"{_pct(s['stopped_by_precision'])} |"
        )
    t = a["at_20"]
    L += [
        "",
        f"At a fixed 20 responses the mean posterior SD is {t['mean_posterior_sd']:.3f} while the mean "
        f"1/sqrt(sum I) is {t['mean_info_se']:.3f} (RMSE {t['rmse']:.3f}).",
        "",
        "## B. Practice",
        "",
        "![B](figures/sim_b_mastery.png)",
        "",
        f"| Policy | Mean true mastery after {cfg['b_steps']} questions | Reached 80% mastery | "
        "Median questions to 80% |",
        "|---|---|---|---|",
    ]
    for name, r in res["B"].items():
        med = r["median_steps_to_80"]
        med_s = f"{med:.0f}" if med <= cfg["b_steps"] else f"> {cfg['b_steps']}"
        L.append(f"| {name} | {_pct(r['mean_final_mastery'])} | {_pct(r['reached_80'])} | {med_s} |")
    em = res["bkt_em"]["params"]
    L += [
        "",
        f"BKT parameters were fit by EM on a separate cohort of random-practice sequences: "
        f"p_init {em['p_init']:.3f}, p_learn {em['p_learn']:.3f}, guess {em['guess']:.3f}, slip {em['slip']:.3f} "
        f"(log-likelihood {res['bkt_em']['loglik_trace'][0]:.1f} to {res['bkt_em']['loglik_trace'][-1]:.1f} "
        f"over {len(res['bkt_em']['loglik_trace'])} iterations).",
        "",
        "## C. Item calibration",
        "",
        "![C](figures/sim_c_calibration.png)",
        "",
        "| Responses per item | " + " | ".join(str(k) for k in res["C"]["rmse_by_responses"]) + " |",
        "|---|" + "---|" * len(res["C"]["rmse_by_responses"]),
        "| RMSE of b-hat | " + " | ".join(f"{v:.3f}" for v in res["C"]["rmse_by_responses"].values()) + " |",
        "",
        f"Label-only baseline (easy/medium/hard mapped to -1/0/+1): RMSE {res['C']['label_only_rmse']:.3f}.",
        "",
        "## D. Evidence sharing",
        "",
        "![D](figures/sim_d_brier.png)",
        "",
        "| Condition | Mean Brier over the session | Mean true mastery at end |",
        "|---|---|---|",
    ]
    for name, r in res["D"].items():
        L.append(f"| {name} | {r['mean_brier']:.4f} | {_pct(r['mean_final_mastery'])} |")
    L.append("")
    return "\n".join(L)
